import React, { useState } from 'react';
import { X, Download, FileText, Check, Copy } from 'lucide-react';
import { BOM_DATA, ASSEMBLY_STEPS } from '../data/shelterData';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const ExportModal: React.FC<ExportModalProps> = ({ isOpen, onClose }) => {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const specMarkdown = `# ARCHITECTURAL & ENGINEERING SPECIFICATION: AEGIS-24
## Archetype 1: Emergency Rapid-Deployment Thermal Shelter
**Document Revision:** 2026.1-RELIEF-STD
**UNHCR / OCHA Standard Compliance:** Sphere Project Shelter Standard 3.1 & 3.2

---

### 1. PHYSICAL DIMENSIONS & GEOMETRY
- Footprint Length: 6.00 m (6,000 mm)
- Footprint Width: 4.00 m (4,000 mm)
- Usable Floor Area: 24.0 m²
- Internal Clear Height (Low Wall / South): 2.40 m (2,400 mm)
- Internal Clear Height (Ridge Wall / North): 3.47 m (3,470 mm)
- Enclosed Volume: 70.4 m³ gross / 57.6 m³ conditioned net
- Roof Pitch Slope: 15.0° (mono-pitch water/snow shedding gradient)
- Ground Standoff Clearance: 150 mm nominal (8 adjustable helical screw footings)

---

### 2. STRUCTURAL FRAMING
- Material: Cold-formed Lightweight Galvanized Steel Framing (LGSF) Grade G550 (Z275 zinc coating)
- Alternative Frame: Boron-treated modular structural bamboo hybrid joints
- Exoskeleton Columns: 4× corner C-channel assemblies with integrated stiffening flanges
- Hardware Fasteners: M12 Grade 8.8 hot-dip galvanized hex-bolt assemblies with EPDM isolation washers
- Wet Curing Requirement: ZERO WET CURING (Dry mechanical joints only)
- Design Wind Resistance: 140 km/h (Category 1 hurricane / acute storm rating)
- Design Seismic Load: Zone 4 (Ductile moment-resisting frame)

---

### 3. THERMAL ENVELOPE & WATERPROOFING
- Wall Panels: 75mm PIR (Polyisocyanurate) closed-cell sandwich core (R-28.4 / U=0.20 W/m²K)
- Facings: 0.5mm matte pre-weathered steel skins (Olive Drab external / Warm White internal)
- Joints: Precision tongue-and-groove with dual continuous EPDM vapor gaskets
- Roof Deck: 15° pitched corrugated composite panels with radiant thermal foil barrier (R-31.5)
- Fenestration: 2× South-facing 16mm multi-wall polycarbonate impact-resistant glazed apertures (1.2m × 0.8m)
- Aperture: Insulated storm door with magnetic perimeter seal and heavy-duty storm cam-latch

---

### 4. LOGISTICS & ASSEMBLY
- Gross Dry Weight: 1,061.9 kg
- Packaging Volume: 6.8 m³ (flat-packed)
- Crew Requirement: 4 operators (no specialized trade skills required)
- Target Field Assembly Time: 4.1 hours (250 minutes)
- Foundation Anchoring: 8× 850mm helical earth screws driven to refusal

---
Generated by Aegis-24 3D Architectural Visualizer`;

  const handleDownload = () => {
    const blob = new Blob([specMarkdown], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'Aegis-24_Archetype1_Thermal_Shelter_Spec.md';
    link.click();
    URL.revokeObjectURL(url);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(specMarkdown);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/75 backdrop-blur-md">
      <div className="relative w-full max-w-3xl bg-slate-900 border border-slate-700 rounded-2xl shadow-2xl overflow-hidden flex flex-col max-h-[90vh] text-slate-100">
        {/* Header */}
        <div className="px-6 py-4 border-b border-slate-800 flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <FileText className="w-5 h-5 text-sky-400" />
            <div>
              <h3 className="text-base font-bold text-white">
                Architectural & Engineering Specification Export
              </h3>
              <p className="text-xs text-slate-400">
                Archetype 1 Emergency Rapid-Deployment Shelter (24 m²)
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Spec Preview Area */}
        <div className="p-6 overflow-y-auto font-mono text-xs text-slate-300 leading-relaxed bg-slate-950/70 select-text whitespace-pre-wrap">
          {specMarkdown}
        </div>

        {/* Actions Footer */}
        <div className="px-6 py-4 border-t border-slate-800 bg-slate-900 flex items-center justify-between">
          <button
            onClick={handleCopy}
            className="flex items-center gap-2 px-3.5 py-2 text-xs font-medium text-slate-300 hover:text-white bg-slate-800 hover:bg-slate-700 rounded-lg transition-colors"
          >
            {copied ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
            <span>{copied ? 'Copied to Clipboard' : 'Copy Spec Markdown'}</span>
          </button>

          <button
            onClick={handleDownload}
            className="flex items-center gap-2 px-4 py-2 text-xs font-semibold text-white bg-sky-600 hover:bg-sky-500 rounded-lg transition-colors shadow-md shadow-sky-950"
          >
            <Download className="w-4 h-4" />
            <span>Download .MD Spec Document</span>
          </button>
        </div>
      </div>
    </div>
  );
};
